import faces from 'virtual:folio-fonts';

function faceCSS(face: (typeof faces)[number], url = face.url) {
  return `@font-face{font-family:"${face.name}";font-style:normal;font-weight:400;font-display:swap;src:url("${url}") format("woff2");unicode-range:${face.range}}`;
}
export const fontCSS = faces.map((face) => faceCSS(face)).join('\n');
export function intersectsRange(range: string, text: string) {
  const points = new Set([...text].map((char) => char.codePointAt(0)!));
  return range.split(',').some((part) => {
    const [low, high] = part.trim().replace(/^U\+/i, '').split('-');
    // `?` is a wildcard digit, not part of the compared number: `U+00??` covers
    // 0x00-0xFF, so those bits must be shifted out before comparing. Without it
    // every low code point "matches" and unused shards get embedded.
    const bits = (low.match(/\?/g) || []).length * 4;
    const start = parseInt(low.replaceAll('?', '0'), 16) >>> bits;
    const end = parseInt((high || low.replaceAll('?', 'F')).replaceAll('?', 'F'), 16) >>> bits;
    if (Number.isNaN(start) || Number.isNaN(end)) return false;
    return [...points].some((point) => point >>> bits >= start && point >>> bits <= end);
  });
}
/**
 * Fontsource 只提供 unicode-range 分片，导出时按分片挑选即可，无需嵌入整套字体。
 * 字体栈里的每个家族都记为候选（浏览器可能因缺字回退），再用 unicode-range
 * 过滤：没有覆盖到文档字符的家族自然被排除，因此嵌入量只与正文用到的字符相关。
 */
export function neededFontFaces(root: HTMLElement) {
  const usage = new Map<string, Set<string>>();
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node: Node | null;
  while ((node = walker.nextNode())) {
    const parent = node.parentElement;
    if (!parent || !node.textContent?.trim()) continue;
    const families = getComputedStyle(parent)
      .fontFamily.split(',')
      .map((name) => name.trim().replace(/^['"]|['"]$/g, ''));
    // List markers are generated by CSS and are not text nodes in the DOM.
    const text = node.textContent + (parent.closest('li') ? '0123456789.•◦' : '');
    for (const family of families) {
      const chars = usage.get(family) || new Set<string>();
      for (const char of text) chars.add(char);
      usage.set(family, chars);
    }
  }
  return faces.filter(
    (face) =>
      usage.has(face.name) && intersectsRange(face.range, [...usage.get(face.name)!].join('')),
  );
}
const embedded = new Map<string, Promise<string>>();
function embed(url: string) {
  let promise = embedded.get(url);
  if (!promise) {
    promise = fetch(url)
      .then(async (response) => {
        if (!response.ok) throw new Error('字体分片加载失败，请重试');
        const blob = await response.blob();
        return new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = () => resolve(String(reader.result));
          reader.onerror = () => reject(new Error('字体嵌入失败'));
          reader.readAsDataURL(blob);
        });
      })
      .catch((error) => {
        embedded.delete(url);
        throw error;
      });
    embedded.set(url, promise);
  }
  return promise;
}
export async function embeddedFontCSS(root: HTMLElement) {
  const selected = neededFontFaces(root),
    output: string[] = [];
  // Keep export requests bounded even for documents spanning many Unicode ranges.
  for (let i = 0; i < selected.length; i += 6) {
    output.push(
      ...(await Promise.all(
        selected.slice(i, i + 6).map(async (face) => faceCSS(face, await embed(face.url))),
      )),
    );
  }
  return output.join('\n');
}
